// GENERATED by scripts/generate-models.ts — DO NOT EDIT.
// Regenerate with `bun run gen:models`.
//
// Static imports of the per-provider catalog chunks: the bundler embeds every
// chunk as raw text, but a provider's body is JSON.parsed only on first
// access (see ../models.ts), so module evaluation never materializes the
// full catalog.
import aiand from "./aiand.json.txt";
import aimlapi from "./aimlapi.json.txt";
import alibabaCodingPlan from "./alibaba-coding-plan.json.txt";
import alibabaTokenPlan from "./alibaba-token-plan.json.txt";
import amazonBedrock from "./amazon-bedrock.json.txt";
import anthropic from "./anthropic.json.txt";
import azure from "./azure.json.txt";
import baseten from "./baseten.json.txt";
import bedrockMantle from "./bedrock-mantle.json.txt";
import cerebras from "./cerebras.json.txt";
import cloudflareAiGateway from "./cloudflare-ai-gateway.json.txt";
import coreweave from "./coreweave.json.txt";
import cursor from "./cursor.json.txt";
import deepseek from "./deepseek.json.txt";
import devin from "./devin.json.txt";
import firepass from "./firepass.json.txt";
import fireworks from "./fireworks.json.txt";
import githubCopilot from "./github-copilot.json.txt";
import gitlabDuo from "./gitlab-duo.json.txt";
import gitlabDuoAgent from "./gitlab-duo-agent.json.txt";
import gmiCloud from "./gmi-cloud.json.txt";
import google from "./google.json.txt";
import googleAntigravity from "./google-antigravity.json.txt";
import googleGeminiCli from "./google-gemini-cli.json.txt";
import googleVertex from "./google-vertex.json.txt";
import groq from "./groq.json.txt";
import huggingface from "./huggingface.json.txt";
import kilo from "./kilo.json.txt";
import kimiCode from "./kimi-code.json.txt";
import meta from "./meta.json.txt";
import minimax from "./minimax.json.txt";
import minimaxCn from "./minimax-cn.json.txt";
import minimaxCode from "./minimax-code.json.txt";
import minimaxCodeCn from "./minimax-code-cn.json.txt";
import mistral from "./mistral.json.txt";
import moonshot from "./moonshot.json.txt";
import nanogpt from "./nanogpt.json.txt";
import novita from "./novita.json.txt";
import nvidia from "./nvidia.json.txt";
import ollamaCloud from "./ollama-cloud.json.txt";
import openai from "./openai.json.txt";
import openaiCodex from "./openai-codex.json.txt";
import opencode from "./opencode.json.txt";
import opencodeGo from "./opencode-go.json.txt";
import opencodeZen from "./opencode-zen.json.txt";
import openrouter from "./openrouter.json.txt";
import qianfan from "./qianfan.json.txt";
import qwenPortal from "./qwen-portal.json.txt";
import sakana from "./sakana.json.txt";
import synthetic from "./synthetic.json.txt";
import together from "./together.json.txt";
import umans from "./umans.json.txt";
import venice from "./venice.json.txt";
import vercelAiGateway from "./vercel-ai-gateway.json.txt";
import waferServerless from "./wafer-serverless.json.txt";
import xai from "./xai.json.txt";
import xaiOauth from "./xai-oauth.json.txt";
import xiaomi from "./xiaomi.json.txt";
import xiaomiTokenPlanAms from "./xiaomi-token-plan-ams.json.txt";
import xiaomiTokenPlanCn from "./xiaomi-token-plan-cn.json.txt";
import xiaomiTokenPlanSgp from "./xiaomi-token-plan-sgp.json.txt";
import yoloAuto from "./yolo-auto.json.txt";
import zai from "./zai.json.txt";
import zenmux from "./zenmux.json.txt";
import zhipuCodingPlan from "./zhipu-coding-plan.json.txt";

export const MODEL_CHUNKS: Record<string, string> = {
	aiand,
	aimlapi,
	"alibaba-coding-plan": alibabaCodingPlan,
	"alibaba-token-plan": alibabaTokenPlan,
	"amazon-bedrock": amazonBedrock,
	anthropic,
	azure,
	baseten,
	"bedrock-mantle": bedrockMantle,
	cerebras,
	"cloudflare-ai-gateway": cloudflareAiGateway,
	coreweave,
	cursor,
	deepseek,
	devin,
	firepass,
	fireworks,
	"github-copilot": githubCopilot,
	"gitlab-duo": gitlabDuo,
	"gitlab-duo-agent": gitlabDuoAgent,
	"gmi-cloud": gmiCloud,
	google,
	"google-antigravity": googleAntigravity,
	"google-gemini-cli": googleGeminiCli,
	"google-vertex": googleVertex,
	groq,
	huggingface,
	kilo,
	"kimi-code": kimiCode,
	meta,
	minimax,
	"minimax-cn": minimaxCn,
	"minimax-code": minimaxCode,
	"minimax-code-cn": minimaxCodeCn,
	mistral,
	moonshot,
	nanogpt,
	novita,
	nvidia,
	"ollama-cloud": ollamaCloud,
	openai,
	"openai-codex": openaiCodex,
	opencode,
	"opencode-go": opencodeGo,
	"opencode-zen": opencodeZen,
	openrouter,
	qianfan,
	"qwen-portal": qwenPortal,
	sakana,
	synthetic,
	together,
	umans,
	venice,
	"vercel-ai-gateway": vercelAiGateway,
	"wafer-serverless": waferServerless,
	xai,
	"xai-oauth": xaiOauth,
	xiaomi,
	"xiaomi-token-plan-ams": xiaomiTokenPlanAms,
	"xiaomi-token-plan-cn": xiaomiTokenPlanCn,
	"xiaomi-token-plan-sgp": xiaomiTokenPlanSgp,
	"yolo-auto": yoloAuto,
	zai,
	zenmux,
	"zhipu-coding-plan": zhipuCodingPlan,
};
